- scripts/promote-tracks.py
The `.days` field only returns full days. Hence, checking for `>` would wait one day more than specified.
> Consider the exact number of days to stay in risk level

- .github/workflows/create-release-branch.yaml
- scripts/ensure_snap_builds.py
- scripts/util.py
The workflow encountered errors when it was creating new snap recipes
* https://github.com/canonical/canonical-kubernetes-release-ci/actions/runs/10884641233
* Addresses ux/usability to not require a user to provide a branch
* Adds a `dry-run` option from GH CI
* Ensures correct processors selection (hard coded for now)
> Creation of new snap recipes encountering errors

- .github/workflows/naming-lint-unit.yaml
- .github/workflows/promotion.yaml
- .github/workflows/rebuild-release-branch.yaml
- .github/workflows/upgrade-proposal-test.yaml
- pyproject.toml
- scripts/ensure_snap_builds.py
- scripts/promote_tracks.py
- scripts/request_builds.py
- scripts/requirements.txt
- scripts/util/gh.py
- scripts/util/lp.py
- scripts/util/repo.py
- scripts/util/util.py
- test_requirements.txt
- tests/unit/test_promote_tracks.py
- tests/unit/util/test_lp.py
- tests/unit/util/test_repo.py
- tests/unit/util/test_snapstore.py
- tests/unit/util/test_util.py
- tox.ini
In order for `<track>/<risk>` to replace `<track>/<risk+1>`, We need to validate upgrades
* from `<track>/<risk+1>` to `<track>/<risk>`
* from `<track>/<highest>` to `<track>/<risk>`
* from `<prior-track>/<highest>` to `<track>/<risk>`
example)
promoting 1.31/edge -> 1.31/beta:
* validate 1.31/beta -> 1.31/edge  (ensures some revision on the beta channel gets a safe auto-refresh)
* validate 1.31/stable -> 1.31/edge (ensures some revision on a stable channel gets this rev as an auto-refresh)
* validate 1.30/stable -> 1.31/edge (ensure some revision on a prev stable gets this rev during channel switch)
* Add CI unit tests for "promote_tracks"
* Unifies logging of the promote_tracks job with the ensure_snap_builds job
* uses ruff for formatting, and ruff isort and mypy for linting
* Ensures …
> Validated promotion k8s-snap revisions can be upgraded to

- .github/workflows/promotion.yaml
- .github/workflows/upgrade-proposal-test.yaml
- scripts/promote_tracks.py
- tests/unit/test_promote_tracks.py
In order to run the promote workflow from the action, the `ignored-tracks` and `ignore-arches` should support an empty set of arguments.
See failed run:
* https://github.com/canonical/canonical-kubernetes-release-ci/actions/runs/11292884151
* Improves workflow names
* resolves issue when there is no prior snap reversion to upgrade from
> Allow for 0-n args for ignored fields

- .github/workflows/upgrade-proposal-test.yaml
Requires: https://github.com/canonical/k8s-snap/pull/769
Note that the test will still fail until we ported the main branch to 1.31
> Set minimum release for upgrade tests

- .github/workflows/promotion.yaml
They are not supported and cause issues with the upgrade tests.
> Ignore 1.30 tracks in promotion

- scripts/ensure_snap_builds.py
The snap recipe creation fails with:
```
Traceback (most recent call last):
File "/home/runner/work/canonical-kubernetes-release-ci/canonical-kubernetes-release-ci/scripts/ensure_snap_builds.py", line 186, in <module>
main()
File "/home/runner/work/canonical-kubernetes-release-ci/canonical-kubernetes-release-ci/scripts/ensure_snap_builds.py", line 179, in main
prepare_track_builds(branch, args)
File "/home/runner/work/canonical-kubernetes-release-ci/canonical-kubernetes-release-ci/scripts/ensure_snap_builds.py", line 151, in prepare_track_builds
ensure_lp_recipe(flavour, ver, channels, tip, args.dry_run)
File "/home/runner/work/canonical-kubernetes-release-ci/canonical-kubernetes-release-ci/scripts/ensure_snap_builds.py", line 104, in ensure_lp_recipe
recipe = (not dry_run) and …
```
> Fix snap recipe creation

- .github/workflows/promotion.yaml
The workflow is failing in subsequent steps due to an empty matrix. See https://github.com/canonical/canonical-kubernetes-release-ci/actions/runs/12274025745/job/34246068787
> Don't fail workflow if no revision needs promotion

- .github/workflows/promotion.yaml
- scripts/promote_tracks.py
- tests/unit/test_promote_tracks.py
We don't support 1.30 and the strict version of the snap (right now), which makes it unnecessary to run the promotion/upgrade tests for those versions.
Updated the `ignored_tracks` parameter to support regexp to support strict channel.
> Use regexp to ignore tracks

- .github/workflows/upgrade-proposal-test.yaml
The upgrate tests time out while waiting for the cilium image
to be downloaded.
Note that we have a large amount of parallel tests (~100) that
do not share the same env and cannot benefit from the image
proxy, leading to a large number of image downloads.
For now, we'll increase the test timeouts.
> Increase test timeouts

- scripts/promote_tracks.py
We'll add a check to avoid automatically promoting pre-releases to tracks such as beta, candidate or stable.
> Avoid promoting pre-releases

- scripts/promote_tracks.py
- scripts/util/util.py
- tests/unit/test_promote_tracks.py
Looks like the snap info already contains the packaged k8s version, so we don't actually have to download the snaps and unsquash them.
> Avoid pulling snaps to detect version

- scripts/util/snapstore.py
- tests/unit/util/test_snapstore.py
This commit ensures the creation of snap tracks for a release if they do not already exist. It interacts directly with the charmhub.io API (not snapstore.io) to create any missing tracks. Only new tracks that conform to the naming guard-rails (1.XX[-classic|strict|moonray]) will be automatically created.
Highly inspired by: https://github.com/canonical/canonical-kubernetes-release-ci/pull/22
> Create missing snap tracks if necessary

- scripts/ensure_snap_builds.py
Pass the tracks (e.g. 1.33-classic) to ensure_track instead of the channel (e.g. 1.33-classic/edge).
See https://github.com/canonical/canonical-kubernetes-release-ci/actions/runs/13001135531/job/36259892507
Follow up fix for https://github.com/canonical/canonical-kubernetes-release-ci/pull/24
> Ensure unique tracks in the snapstore

- scripts/ensure_snap_builds.py
The strict flavor is currently broken and unsupported. We'll disable the "auto-build" launchpad recipe flag for now.
> Disable auto-build flag for strict flavor

- .github/workflows/update-pre-release-branches.yaml
- scripts/k8s_release.py
- scripts/promote_tracks.py
- scripts/publish_k8s_debs.py
- scripts/util/k8s.py
- tests/unit/test_k8s_release.py
- tests/unit/test_promote_tracks.py
- tests/unit/util/test_k8s.py
- tox.ini
Right now, only the latest pre-release is supported. However, in transistion times there might be multiple non-stable releases (e.g. 1.33.0-rc1 and 1.34.0-alpha) which both need to be supported.
Also, refactored the common k8s functions and added test-coverage.
> feat: Support multiple pre-releases

- scripts/promote_tracks.py
The nightly promotion job is very inconsistent about which `test_version_upgrades.py` it runs and it could be linked to these choices of which branches run the promotion:
in some instances i see:
```
tox -e promote -- \
\
test \
--branch="release-1.32"
```
lead to:
```
util.repo 2025-04-15 14:19:01,759     INFO - Cloning https://github.com/canonical/k8s-snap.git/ @ main (shallow=True)
Cloning into '/tmp/tmpeup1vhe5'...
promote_tracks 2025-04-15 14:19:03,278     INFO - Running integration tests for main
```
and others:
```
util.repo 2025-04-15 00:08:18,054     INFO - Cloning https://github.com/canonical/k8s-snap.git/ @ release-1.32 (shallow=True)
Cloning into '/tmp/tmpbhte762t'...
promote_tracks 2025-04-15 00:08:19,505     INFO - Running integration tests for release-1.32
```
The ones from …
> Run integration tests from the release branch only

- .github/workflows/update-pre-release-branches.yaml
- scripts/k8s_release.py
- scripts/util/snapstore.py
- tests/unit/util/test_snapstore.py
Follow-up fix for #29. Invalid workflows are not marked as failed, hence this slipped through.
Also, refactors the `track exists` check to always try to create the track in the snapstore. If it already exists we get a 409 code back which can be ignored.
We need to do this since the unpopulated tracks are not returned by the snap info API.
> fix: Fix pre-release check

- .github/workflows/promotion.yaml
- .github/workflows/upgrade-proposal-test.yaml
The self-hosted runners container docker with causes issues with docker iptable conflicts.
This PR allows LXD traffic on the hosts again.
> fix: Allow LXD traffic in iptable rules

- .github/workflows/promotion.yaml
- .github/workflows/publish-k8s-debs.yaml
- scripts/publish_k8s_debs.py
- scripts/templates/publish_k8s_debs/Makefile.j2
- scripts/util/repo.py
This PR improves the logic to build and publish deb packages to Launchpad.
- Use nested tmp directories to enable reproducible builds.
- Add GPG import step
- Add `--stable-ppa` option to enable uploading to a test PPA
- Rename `BOT_` environment variables to `DEBS_` to better convey how/where they should be used.
- Remove debs job from CI:
- Running the debs jobs on PR is not practical right now because `version postfix` needs to be unique and semantically greater than what is already available in the PPA. Hard coding it will only cause in failed jobs which is not useful. Later on we need to come up with a mechanism to automatically select a deb version postfix to prevent conflicts.
> chore: Improve packaging logic. Add test PPA option

- scripts/charm_release.py
- scripts/util/sqa.py
- tests/unit/util/test_sqa.py
The SQA `productversion` endpoint does not support the `version` parameter for Canonical k8s and therefore we should use k8s charm revision as the identifier. This will resolve the issue with SQA platform but requires additional assumption that k8s-worker charm will not have any new revisions on track/candidate unless there is a new revision on k8s charm track/candidate as well. Otherwise, the automation will promote k8s-worker charm without a test.
> chore: switch to productversion revision from version

- .github/workflows/promotion.yaml
The moonray flavor is no longer needed, therefore this PR removes all mention of it.
Moonray tracks are already closed.
> chore: rm moonray reference
